### ISSUE TITLE
qt-sni doesn't like the size of your main icon

### ISSUE THREAD

**Issue by JasonLG1979** [JeffHoogland/qAndora#12] opened 2015-02-10 15:55 UTC
I don't know why (other than maybe qt-sni expects "standard" sized icons?) but after installing qt-sni I got a broken image icon for the system tray icon in Kubuntu 14.04. After I resized the icon to 256 x 256 px it displays fine.

**Comment by JeffHoogland** [comment] 2015-02-10 16:02
Sounds like a bug in the systray.

**Comment by JasonLG1979** [comment] 2015-02-10 16:04
Or a bug in qt-sni since the icon shows up just fine as long as qt-sni isn't installed.

**Comment by JasonLG1979** [comment] 2015-02-10 16:06
In any case no matter where the bug the fix/workaround is as easy as resizing the icon to 256x256

**Comment by JasonLG1979** [comment] 2015-02-16 22:33
The icon shows up as a broken/missing image in the Ubuntu panel also.

**Comment by JeffHoogland** [comment] 2015-10-27 17:48
I'm closing this as invalid / not a bug in this project. The icon appears as expected in Moksha's systray and KDE 4 last I checked.

**Closed by JeffHoogland** 2015-10-27 17:48 UTC
